name: "omnip"
version: "1.0.0"
profile: "omnip"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  omnip:
    2_silver:
      +materialized: view
    3_gold:
      +materialized: table
