name: "omnip"
version: "1.0.0"
profile: "omnip"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  omnip:
    # Прибираємо +materialized: view звідси,
    # щоб працював 'incremental' з SQL-файлу
    2_silver:
      +schema: silver # бажано додати назву схеми для порядку
    3_gold:
      +materialized: table
      +schema: gold
