name: Run NBU Ingestion and dbt

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: nbu-app:latest
          outputs: type=docker,dest=/tmp/nbu-app.tar

      - name: Load Docker image
        run: docker load --input /tmp/nbu-app.tar

      - name: Run Scraper and dbt (Inside Docker)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_STAGING_DIR: ${{ secrets.AWS_S3_STAGING_DIR }}
          ATHENA_DATABASE: ${{ secrets.ATHENA_DATABASE }}
          ATHENA_SCHEMA: ${{ secrets.ATHENA_SCHEMA }}
        run: |
          docker run --rm \
            -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -e AWS_REGION="${{ secrets.AWS_REGION }}" \
            -e AWS_S3_STAGING_DIR="${{ secrets.AWS_S3_STAGING_DIR }}" \
            -e ATHENA_DATABASE="${{ secrets.ATHENA_DATABASE }}" \
            -e ATHENA_SCHEMA="${{ secrets.ATHENA_SCHEMA }}" \
            nbu-app sh -c "python src/ingest_nbu_rates.py && cd dbt && dbt build --full-refresh"

      # --- Блок для генерації анімації ---
      - name: Set up Python for Visualization
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Viz Dependencies
        run: pip install pandas matplotlib seaborn pyathena pillow boto3

      - name: Generate GIF Animation
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_STAGING_DIR: ${{ secrets.AWS_S3_STAGING_DIR }} # Використовуємо ту саму назву, що в visualize_rates.py
        run: python src/visualize_rates.py

      - name: Upload Analysis Artifact
        uses: actions/upload-artifact@v4
        with:
          name: currency-animation
          path: usd_eur_bivariate.png
